Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Task.DB.Models;
using MVC_Task.Services.CourseService;
using MVC_Task.Services.DepartmentService;

namespace MVC_Task.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IDepartmentService _departmentService;

        public CourseController(ICourseService courseService , IDepartmentService departmentService)
        {
            _courseService = courseService;
            _departmentService = departmentService;
        }

        public async Task<IActionResult> Index()
        {
            var courses = await _courseService.GetAll();
            return View(courses.Data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var course = await _courseService.Get(id);
            if (course.IsSuccess == false)
            {
                return NotFound();
            }
            return View(course.Data);
        }

        public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseService.Add(course);
                return RedirectToAction(nameof(Index));
            }

            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            return View(course);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseService.Get(id);
            if (course.Data == null)
            {
                return NotFound();
            }
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            return View(course.Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course course)
        {
            if (ModelState.IsValid)
            {
                var updateResult = await _courseService.Update(id, course);
                if (!updateResult.IsSuccess)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            return View(course);
        }

        // GET: Course/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var course = await _courseService.Get(id);
            if (course.Data == null)
            {
                return NotFound();
            }
            return View(course.Data);
        }

        [HttpPost , ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _courseService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        
    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Task.Services.DepartmentService;
using MVC_Task.DB.Models;

namespace MVC_Task.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _departmentService.GetAll();
            return View(response.Data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var response = await _departmentService.Get(id);
            if (response == null) return NotFound();
            return View(response.Data);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department department)
        {
            if (!ModelState.IsValid) return View(department);
            await _departmentService.Add(department);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _departmentService.Get(id);
            if (response == null) return NotFound();
            return View(response.Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Department department)
        {
            if (!ModelState.IsValid) return View(department);
            await _departmentService.Update(id, department);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _departmentService.Get(id);
            if (response == null) return NotFound();
            return View(response.Data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _departmentService.Delete(id);
            if (!result.IsSuccess) return NotFound();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Task.Services.InstructorService;
using MVC_Task.DB.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Task.Services.DepartmentService;
using MVC_Task.Services.CourseService;
using Azure;

namespace MVC_Task.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IInstructorService _instructorService;
        private readonly IDepartmentService _departmentService;
        private readonly ICourseService _courseService;

        public InstructorController(IInstructorService instructorService , IDepartmentService departmentService , ICourseService courseService)
        {
            _instructorService = instructorService;
            _departmentService = departmentService;
            _courseService = courseService;

        }

        public async Task<IActionResult> Index()
        {
            var result = await _instructorService.GetAll();
            return View(result.Data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var result = await _instructorService.Get(id);
            if (!result.IsSuccess)
            {
                return NotFound();
            }
            return View(result.Data);
        }

        public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.GetAll();
            var courses = await _courseService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            ViewBag.Courses = new SelectList(courses.Data.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                var result = await _instructorService.Add(instructor);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.ErrorList)
                {
                    ModelState.AddModelError(error.PropertyName, error.Message);
                }
            }
            var departments = await _departmentService.GetAll();
            var courses = await _courseService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            ViewBag.Courses = new SelectList(courses.Data.ToList(), "Id", "Name");
            return View(instructor);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var result = await _instructorService.Get(id);
            if (!result.IsSuccess)
            {
                return NotFound();
            }
            var departments = await _departmentService.GetAll();
            var courses = await _courseService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            ViewBag.Courses = new SelectList(courses.Data.ToList(), "Id", "Name");
            return View(result.Data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                var result = await _instructorService.Update(id, instructor);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.ErrorList)
                {
                    ModelState.AddModelError(error.PropertyName, error.Message);
                }
            }
            var departments = await _departmentService.GetAll();
            var courses = await _courseService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            ViewBag.Courses = new SelectList(courses.Data.ToList(), "Id", "Name");
            return View(instructor);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _instructorService.Get(id);
            if (!result.IsSuccess)
            {
                return NotFound();
            }
            return View(result.Data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _instructorService.Delete(id);
            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }

            return NotFound();


        }
    }
}

Controllers/TraineeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_Task.DB.Models;
using MVC_Task.Services.DepartmentService;
using MVC_Task.Services.TraineeService;


namespace MVC_Task.Controllers
{
    public class TraineeController : Controller
    {
        private readonly ITraineeService _traineeService;
        private readonly IDepartmentService _departmentService;

        public TraineeController(ITraineeService traineeService , IDepartmentService departmentService)
        {
            _traineeService = traineeService;
            _departmentService = departmentService;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _traineeService.GetAll();
            return View(response.Data); 
        }

        public async Task<IActionResult> Details(int id)
        {
            var response = await _traineeService.Get(id);
            if (response.IsSuccess)
            {
                return View(response.Data);
            }

            return NotFound();
        }

        public async Task<IActionResult> Create()
        {
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");

            return View();
        }

        // POST: Trainee/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                var response = await _traineeService.Add(trainee);
                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");

            return View(trainee);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var response = await _traineeService.GetById(id);
            if (response.IsSuccess)
            {
                var departments = await _departmentService.GetAll();
                ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
                return View(response.Data);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                var response = await _traineeService.Update(id, trainee);
                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            var departments = await _departmentService.GetAll();
            ViewBag.Departments = new SelectList(departments.Data.ToList(), "Id", "Name");
            return View(trainee);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _traineeService.GetById(id);
            if (response.IsSuccess)
            {
                return View(response.Data);
            }

            return NotFound();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _traineeService.Delete(id);
            if (response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }

            return NotFound(); 
        }
    }
}

Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Education App</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Education App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Trainee" asp-action="Index">Trainees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Course" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Department" asp-action="Index">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Instructor" asp-action="Index">Instructors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="CourseResult" asp-action="Index">Course Results</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container mt-4">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="bg-dark text-white text-center py-4 mt-5">
        <div class="container">
            <p class="mb-0">&copy; @DateTime.Now.Year Education App. All rights reserved.</p>
        </div>
    </footer>

    <!-- Bootstrap JS and Dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Custom JS -->
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Task.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_Task - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>